version: '3'

services:
  jupyter:
    build: ./jupyter
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"
    volumes:
      - ./jupyter/data:/home/jovyan/work
      - ./jupyter/notebooks:/home/jovyan/notebooks
    networks:
      - minio-network
    command: start-notebook.sh --notebook-dir=/home/jovyan/notebooks

  minio:
    build: ./minio
    ports:
      - '${MINIO_API_PORT}:${MINIO_API_PORT}'
      - '${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}'
    volumes:
      - ./minio/data:/data
    networks:
      - minio-network
    environment:
      MINIO_ROOT_USER: '${MINIO_ROOT_USER}'
      MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD}'
      MINIO_ADDRESS: ':${MINIO_API_PORT}'
      MINIO_CONSOLE_ADDRESS: ':${MINIO_CONSOLE_PORT}'

networks:
  minio-network:
    driver: bridge
